apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  config.json: |
    {
      "endpoints": {
        {{- range $name, $endpoint := .Values.configData.endpoints }}
        "{{ $name }}": {
          "url": "{{ $endpoint.url }}",
          "timeout": {{ $endpoint.timeout }}
        }{{ if ne $name (last (keys $.Values.configData.endpoints)) }},{{ end }}
        {{- end }}
      }
    }