name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml
    
    - name: Check endpoints
      run: |
        python endpoint_monitor.py fetch --output
      
  build-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/endpoint-monitor:latest,${{ secrets.DOCKER_USERNAME }}/endpoint-monitor:${{ github.sha }}
    
  # Deployment to development environment (using Minikube)
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
    
    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube addons enable storage-provisioner
    
    - name: Deploy using Helm
      run: |
        # Update the image tag to use the current commit SHA
        sed -i "s/tag: latest/tag: ${{ github.sha }}/g" helm/endpoint-monitor/values.yaml
        
        # Install/update the Helm chart
        helm upgrade --install endpoint-monitor ./helm/endpoint-monitor --set replicaCount=1

    - name: Wait for pod to be ready
      run: |
        echo "Waiting for endpoint-monitor pods to appear..."
        
        COUNTER=0
        MAX_TRIES=30
        SLEEP_SECONDS=10

        while [ $COUNTER -lt $MAX_TRIES ]; do
          POD_COUNT=$(kubectl get pods -l app=endpoint-monitor -o jsonpath='{.items}' | jq '. | length')

          if [ "$POD_COUNT" -gt "0" ]; then
            echo "Found endpoint-monitor pods!"
            kubectl get pods -l app=endpoint-monitor
            break
          fi

          echo "No endpoint-monitor pods found yet. Waiting $SLEEP_SECONDS seconds..."
          sleep $SLEEP_SECONDS
          COUNTER=$((COUNTER+1))
        done

        if [ $COUNTER -eq $MAX_TRIES ]; then
          echo "Timeout waiting for pods to appear"

          echo "Current pods in all namespaces:"
          kubectl get pods --all-namespaces

          echo "Current deployments:"
          kubectl get deployments

          echo "Helm releases:"
          helm list

          exit 1
        fi

        echo "Waiting for pod to become ready..."
        kubectl wait --for=condition=ready pod -l app=endpoint-monitor --timeout=300s

    - name: Verify deployment functionality
      run: |
        echo "Verifying endpoint-monitor functionality..."
        
        POD_NAME=$(kubectl get pods -l app=endpoint-monitor -o jsonpath='{.items[0].metadata.name}')

        echo "Running endpoint monitor inside the pod..."
        kubectl exec $POD_NAME -- endpoint-monitor fetch --output
        EXIT_CODE=$?

        if [ $EXIT_CODE -eq 0 ]; then
          echo "Deployment verification successful!"
        else
          echo "Deployment verification failed!"
          kubectl logs $POD_NAME
          exit 1
        fi

    - name: Show pod logs
      run: |
        # List all pods in the cluster
        echo "Listing all pods in the cluster:"
        kubectl get pods --all-namespaces
        
        # List only the endpoint-monitor pod
        echo "Listing only the endpoint-monitor pod:"
        kubectl get pods -l app=endpoint-monitor -o wide
        
        # Get the pod name
        POD_NAME=$(kubectl get pods -l app=endpoint-monitor -o jsonpath='{.items[0].metadata.name}')
        
        # Show detailed information about the pod
        echo "Detailed information about pod $POD_NAME:"
        kubectl describe pod $POD_NAME
        
        # Show logs from the pod
        echo "Showing logs from pod $POD_NAME:"
        kubectl logs $POD_NAME